name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
    - name: Install dependencies
      run: pnpm install
    - name: Run lint
      run: pnpm run lint
    - name: Run unit tests
      run: pnpm run test
    - name: Build
      run: pnpm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run e2e tests
      env:
        GITHUB_ACTIONS: true
      run: pnpm run test:e2e

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9
    - name: Install dependencies
      run: pnpm install
    - name: Build
      env:
        GITHUB_ACTIONS: true
      run: pnpm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist